camera_extrinsic:
  ros__parameters:
    base_frame: "base_link"
    camera_frame: "camera_color_optical_frame"
    translation_xyz: [0.62270570, 0.08602302, 0.87020823]
    rotation_quat_xyzw: [0.72335244, 0.69012262, -0.01827587, 0.01257044]

# manual_calib: samples=4  mean=1.67mm  max=2.04mm

hand_eye_result:
  ros__parameters:
    gripper_frame: "link_6"
    marker_frame: "calibration_aruco_marker"
    gripper_to_marker_xyz: [-0.04032655, 0.09161299, -0.00066978]
    gripper_to_marker_quat_xyzw: [-0.26441589, -0.62651231, -0.2851028, 0.6754872]
    marker_id: 0
    marker_size_m: 0.05
